### ISSUE TITLE
make chapters.yaml error

### ISSUE THREAD

**Issue by vinhphunguyen** [islandoftex/arara#144] opened 2021-12-03 00:11 UTC
Hello,

I have tried to use this make chapters.yaml, from Hughes (https://tex.stackexchange.com/questions/31334/how-to-create-individual-chapter-pdfs-from-included-texs)

```yaml
!config
# Make chapter files rule for arara
# author: Chris Hughes
# last edited by: cmh, May 20th 2013
# http://tex.stackexchange.com/questions/31334/how-to-create-individual-chapter-pdfs
# requires arara 3.0+
#
# Sample usage: Assume you have the following directives in main.tex, with chapter files
#               lions.tex, zebras.tex
#
# % arara: makechapters: {items: [lions]}
# % arara: makechapters: {items: [lions, zebras]}
# % arara: makechapters: {items: [lions, zebras], compileAll: no}
# % arara: makechapters: {items: [lions, zebras], compileAll: yes}
#
# which will create lions.pdf, zebras.pdf
#
# Note that, by default, this compiles main.tex first so that all of the necessary .aux
# files are generated- this is vital for cross referencing to work, particularly in 
# the case of a *forward* cross reference (e.g chapter 2 refers to chapter 3). 
#
# If you set compileAll to false/no/off, then it will *not* compile the main file
# first- be careful with this one, as the necessary .aux files may not be present, and 
# your cross references may break. 
identifier: makechapters
name: MakeChapters
commands: 
- <arara> @{ isTrue( compileAll, engine.concat(' "').concat(file).concat('"') )}
- <arara> @{engine} -jobname=tmpCMH "\includeonly{@{item}}\input{@{file}}" 
- <arara> @{engine} -jobname=tmpCMH "\includeonly{@{item}}\input{@{file}}" 
- <arara> @{ isWindows( "cmd /c move", "mv" ) } tmpCMH.pdf @{item}.pdf
arguments:
- identifier: engine
  flag: <arara> @{parameters.engine}
  default: pdflatex
- identifier: compileAll
  flag: <arara> @{parameters.compileAll}
  default: true
```

------

Arara gave me this:

```
DETAILS ---------------------------------------------------------
com.charleskorn.kaml.IncorrectTypeException at commands[0] on
line 28, column 3: Expected an object, but got a scalar value
```

Could you please help?

**Comment by cereda** [comment] 2021-12-03 11:59
Hi, thanks for reaching out!

This is a _very old_ rule, I will see what I can do. Today is a bit hectic, but I will tackle the rule as soon as possible.

Cheerio!

Paulo

**Comment by cereda** [comment] 2021-12-06 10:39
Hello!

This _might_ work, but I haven't tested it. Also, `compileAll` was replaced by `compile` just for aesthetic reasons. :wink: 

```yaml
!config
identifier: makechapters
name: MC
authors:
- Chris Hughes
commands:
- name: Making chapters
  command: >
    @{
        comms = [];
        if (compile[0] == 'true') {
            comms.add(getCommand(engine, reference.getName()));
        }
        foreach(item: items) {
            comms.add(getCommand(engine, '-jobname=tmpCMH', '\\includeonly{'
                      + item + '}\\input{' + reference.getName() + '}'));
            comms.add(getCommand(engine, '-jobname=tmpCMH', '\\includeonly{'
                      + item + '}\\input{' + reference.getName() + '}'));
            comms.add(getCommand(isWindows([ 'cmd', '/c', 'move'], [ 'mv' ]),
                      'tmpCMH.pdf', item + '.pdf'));
        }
        return comms;
    }
arguments:
- identifier: engine
  flag: >
    @{
        parameters.engine
    }
  default: pdflatex
- identifier: compile
  flag: >
    @{
        parameters.compile
    }
  default: true
- identifier: items
  flag: >
    @{
        if (isList(parameters.items)) {
            return parameters.items;
        }
        else {
            throwError('I was expecting a list of items.');
        }
    }
  required: true
```

Hope that helps. :wink: 

I am closing this issue, but feel free to add any comments.

**Closed by cereda** 2021-12-06 10:39 UTC

**Comment by jowe19** [comment] 2022-03-31 11:21
Thanks for the adaptation of this rule. With the MWE of this [topic](http://tex.stackexchange.com/questions/31334/how-to-create-individual-chapter-pdfs) the rule works fine. But with my lecture notes, it doesn't and in the log file I juste have the message `(MC) Making chapters .................................... FAILURE`. 

Is it possible to get more information on the causes of failure? (sorry I am a total beginner with Arara, and this rule brought me to this package yesterday 😊).

**Comment by cereda** [comment] 2022-04-01 16:53
Hello @jowe19!

These are some suggestions for you to track the issue down and understand why the rule does not work:

1. Enable verbose mode: Run `arara` with the `-v` / `--verbose` flag, so the command output is shown in your terminal. That might be useful to understand if it's something related to your code.

2. Include the log generation: Run `arara` with the `-l` / `--log` flag, so everything that the tool does (from directive discovery to command execution + output) is added to a `arara.log` file in the working directory.

3. Try the dry-run mode to see what's going on before running anything: Run `arara` wilth `-n` / `--dry-run` to go through all the motions of running a command, but with no actual calls.

Options 1 and 2 can be used interchangeably. Option 3 is mutually exclusive to the others.

Hope that helps getting started!

**Comment by jowe19** [comment] 2022-04-04 13:39
Thanks for this tips, the problem was the missing of `shell-escape` option. 

I was wondering if it was possible to manage the list of chapters to compile (`items` in this arara rule) in another way. For example by automatically retrieving the list of chapters present in the `\includeonly` command ?
